services:
  php:
    image: php:8.3-cli
    container_name: php_unit_testing
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["composer"]
